<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - titik tiga</name>
   <tag></tag>
   <elementGuidId>0d088198-00e9-474a-a5b7-479d53aa7aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[td//span[text()='Default User']]//button[@data-ts-section='button-action']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-ts-section = 'button-action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-action-6894513019c71aecc2ca4f12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button-action-6894513019c71aecc2ca4f12</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>338e7aeb-ae9b-4167-b8cb-fe3c20537fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-action-6894513019c71aecc2ca4f12</value>
      <webElementGuid>dc182bf6-211b-4a65-81be-ffe6a4bdfa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center h-4 w-4 border border-offset-0 border-inset border-primary-500 rounded-full pointer-events-auto</value>
      <webElementGuid>c75e1b12-dd52-4beb-8dab-8bd89048d5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ts-section</name>
      <type>Main</type>
      <value>button-action</value>
      <webElementGuid>b5c08512-5683-4f71-84d7-54753ee2f8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>703d7b99-60de-4ffa-95e1-7376a4914356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-action-6894513019c71aecc2ca4f12&quot;)</value>
      <webElementGuid>05497939-1142-40db-beea-fdb5bfd7230b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-action-6894513019c71aecc2ca4f12']</value>
      <webElementGuid>da32f45d-67b0-4696-8aad-5dcebefea40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings-user-settings-user-table']/div/table/tbody/tr/td[11]/div/button</value>
      <webElementGuid>5a5e69e8-d278-4d65-ba91-4b0054c37c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>4f5afeae-ed73-403a-8a3d-3002b82c8393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1'])[1]/preceding::button[6]</value>
      <webElementGuid>e9ea2e65-2075-4987-bc85-e06b487ac81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[3]/preceding::button[6]</value>
      <webElementGuid>e45c9507-19fb-4a74-b1ce-efcf7c5b5f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/button</value>
      <webElementGuid>3cd9ab9d-c827-4fa1-bf17-eb9a6e5e39ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-action-6894513019c71aecc2ca4f12' and @type = 'button']</value>
      <webElementGuid>9fc491fc-039a-4f8b-91e6-d6e2706a7320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
