<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Accounting - Create, Edit, Delete Depreciation Group</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>aae54549-455e-4167-a1e8-1fdf1334845c</testSuiteGuid>
   <testCaseLink>
      <guid>1e47c808-20b0-4246-90f9-383564fd8450</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit - Depreciation Method to Double-Decline</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>216a7538-48f1-40e2-a3a1-7feb5221cff8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit - Depreciation Method - Cancel Changes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b8cd3c6d-dd27-4df0-8f5e-bc27abe969d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create - Depreciation Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba662b2-c4bf-4cf1-a408-5510b7fe9724</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ab0f1dc-3f22-4f46-a6e6-b77f43da032c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4f2b72f-6dd3-4e9a-acff-d7dc33958290</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b8b9204-a9e2-4abe-9387-9cfe9d45e181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Depreciation Group - With cancel create</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5908c774-eb3b-41be-9899-d924a3a458d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73b2f628-c81b-4b81-983f-5c6ec1c5ab81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c51ff703-44c3-4284-bde0-3edbc0041fe7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d95c684c-30d5-4185-9d4f-d5cec4f30e7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Depreciation Group - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b5c20162-320c-40ba-bcc1-c7b4eb3ba12d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Depreciation Group - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4396226-eb6c-4f30-ac31-603797983085</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aa95f53-9168-4ac1-825d-a1ba5a30a7f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5deea648-08ec-43d2-aab5-ce86a2b15b6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>398d6b7d-3739-426d-9f78-1240edd692f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Depreciation Group - With empty field depreciation group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c366f4d2-1219-4d11-abc8-2cf7737e80d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Depreciation Group - With empty field salvage value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2982cbaa-6dfc-4fb3-a7ad-58799bb1fddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Depreciation Group - With empty field useful life</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c7f3198c-eafd-4765-811a-5c776bd66627</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Depreciation Group - With field depreciation group already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d2eddf9-aae2-477e-bc9d-3fe41b820fd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12d7b9c9-165b-4ab9-b2d0-c1b26ac19542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dc85c1d-eb80-45ba-81fa-93d6159c93f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e50e52bb-fc30-4150-9647-2bb9599bec1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Depreciation Group - With field depreciation group over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c04e48f2-3c6e-40be-998a-409db5531998</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit - Depreciation group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ccc3a8f-d2ff-44a8-adce-23e2c08e8bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25438438-1bdf-4cb5-8da3-ef1b2034720e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2123fd2a-0f82-4e31-9bb1-f75346344ee7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aed9c869-0f0f-4df1-9bd1-0d558425d69e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd60e908-5319-42d5-8709-e3017b0cc8ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67cef57c-d233-4f13-b2f8-1c2ec815e914</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a88dd24-c42e-4abb-afb9-58e9ee4d1635</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit Depreciation Group - With cancel edit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>070a7629-0c10-435e-ab61-9d588ab28526</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>740741e5-53a0-4c17-8894-04cc36fda87d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit Depreciation group - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff79452c-fc30-4e1f-bfae-6821c4165eb4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25befd39-285d-4017-8baf-829c2f1f7c37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Deprectiation Group - With empty field depreciation group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3741b5d-bdd9-4995-a7ad-4107a65ec463</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbf01163-ef8f-40c6-92dc-b253ff06f876</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Deprectiation Group - With empty field salvage value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a4b239-6704-471b-877c-afe0759c7542</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dad6a9d-8362-4def-abe8-4cd85f94f375</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Deprectiation Group - With empty field useful life</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d488e89-da5a-4a0c-a3a9-ec65a5d3a543</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f770324c-78ee-4f1e-a378-8432432ac56a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Deprectiation Group - With field depreciation group already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a428ac68-0b5f-41b7-8750-8ad9ac5276e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>533eeafc-47e0-4583-abdc-16eea0cdf896</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06c7d90e-4ec7-4fe7-bec0-acc78368a2fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Deprectiation Group - With field depreciation group over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>908c51cf-cd15-4c2d-81c2-962b6fddd15b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3af0fd4c-693c-4068-901c-2c7e5836b46f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Delete Depreciation Group - With cancel delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be0f3a2c-0aa4-48eb-bfe2-59b0b1016fca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2adeb6b-3580-40f5-85a8-76a825b7fba0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Delete - Depreciation Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>877d638d-8bc9-4189-893f-de09a33d387c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e61e819d-9b7b-42cb-94b1-879372b6dacf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Delete - Depreciation Group (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f23f2b61-9f45-4a21-9526-ad3f6122d235</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
