<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Accounting - Create, Edit, Delete Account Code</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5a609573-e5ab-44df-ae8c-3ec23a19eaaf</testSuiteGuid>
   <testCaseLink>
      <guid>9e632a6c-78d5-4985-ac38-0d9d480766a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create - Account Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>434f89b0-3aef-46f8-a82f-df693d404d42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6794d1f-a51a-4be3-9f29-f9337856d9e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fef0d96c-af20-4381-b6a2-2b7185f6a189</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Account Code - With cancel create</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d4412909-d08f-4786-bfe1-b351af7b781d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Account Code - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fe25149f-a4b3-49b4-a5e6-422c76a304bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Create Account Code - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0452110d-612a-48c2-8ae4-4b0b1b033b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e294d40-dbfe-433d-9ad1-b7958e59e232</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50e1c356-2e2a-47ef-83d5-f674978a4290</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfb5f17a-1c38-46a1-8bea-98dcff3a5670</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8f0d319-089d-4484-8823-12f00c467688</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29a0f4b2-9a4f-4932-b7e0-8efe35507857</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>060f64d2-97b0-49a4-9c2d-4157f2e32fc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account code over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cf16afb6-7155-4c5b-8485-c266c6288b66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dedd73c7-d13f-45d4-a9b5-3b7acb5c81e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb419d0a-e40a-437e-be52-da46952e0f16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a94818e7-151e-4e77-a37b-611000609207</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>998f55fe-5faf-4c9a-baa9-fa0901879a0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Create Account Code - With account name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7a454fa7-c992-458c-9dad-99fb16669120</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Edit - Account Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b468e8-40a9-4e40-8bd3-58543c4131dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65c91d75-5d66-423a-80ef-2f08a8fb7a7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abb176df-5e48-4b03-9923-458a6abaca1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b557bbdf-2367-4ca3-82f5-dca5d3e31d55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4894b40e-faac-42a2-ac5b-f1abb2bf2e1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11bb7f50-e128-40ec-8e99-5e12af2c8dca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43df1843-5650-4cc4-9a65-74a925e813cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eedba23-21d4-4703-92de-c895623fa927</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13a773eb-d6dd-4be2-862f-5233ee87641e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98175000-1493-4021-b7c5-76bffc9a8272</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b50a0a7-d853-4f4e-899a-ff70a27bf71c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account code over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b13d1739-9308-4529-bab8-f600323fed02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e91d4cf-bc55-4329-ba77-21e97bb13d74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3baa0a0b-cbc1-4985-9ae8-404496a06422</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b692b102-242d-4361-8375-54bf965f7f3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74fdbab1-45cf-4877-bb80-61615f2f064f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0ebcdf-a870-434c-be86-1bda2cb1e3d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cf55f0b-ad98-4c3a-8059-de93f36c9c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16001ef5-9c54-4f64-9db6-04c8c33305fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0257bece-6368-472e-993b-da339ebfaace</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Negative/Edit Account Code - With account name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>183675fb-68ff-4068-9f24-11190230435f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7beb4f5f-0307-4832-b6b9-eb8f3ece8dd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Delete - Account Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca3e0cd4-e4ee-4a00-b46e-e900f97c6dfe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d61f8a65-21ee-4cb6-b0f2-c6393a2ba466</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Accounting/Positive/Delete - Account Code (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6885b2-f099-40f7-8659-f3750197bcdf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
