<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Asset Name - Create, Edit, Delete Measurement, Brand, Asset Name (Without asset)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>81410406-5e25-488b-869a-c6b1b3683565</testSuiteGuid>
   <testCaseLink>
      <guid>142f1e6c-d5aa-4279-bf61-1a192b9ae69a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create - Measurement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f83171a-f107-42da-a6c9-8b255b53c902</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a8cf4b0-cc25-4a8a-b3a5-1008f0f23355</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Measurement - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>87d7a706-61d3-4dfa-b536-ea462247b771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Measurement - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11120b09-d895-449d-9d30-8bf2a86e4a50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a90197ca-55e0-4193-a7f6-e499fec19b17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Measurement - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21843660-09d2-447e-81f4-93c4d9733fb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfb76fc1-44f8-429d-bb30-e472cb532c7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Measurement - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f2e7d79b-f839-45f1-bb3f-c0448115ec2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Measurement - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9b778787-3aa9-45ee-b303-aab9967a2487</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit - Measurement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>047aa556-4597-4cbb-8236-8b6636d1dd7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a74b206-f7ab-4af7-b673-fd1bfe92886f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8073c37d-6a06-4fbc-add2-1f386e6358dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit Measurement - With cancel edit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0087e98-e2a9-4f1e-b122-d7555f5230a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b58faa5-cb26-49e5-a149-52c90f83a040</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit Measurement - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98b5d2a8-6215-453f-bd04-9db8f9d34d69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adb5506f-ba7d-409b-bce4-0c6f9b48aeba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Measurement - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00ae9723-ba71-46d0-83ee-8c6d5e95e2e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac85d108-540d-40e7-a87d-f1cfac3e4967</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Measurement - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aaf4345-7d21-41c6-a68b-55707cb2ef4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>728e7230-3b46-485e-8a79-da76e0b932b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Measurement - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce304f04-b357-4b04-98a6-e60df4fe8ec4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f2a65e2-a1c5-46b1-bf42-68af73b6eaf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create - Brand</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3f56a5d-03ec-45d3-8f95-85b509c97644</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e10617-1dee-42a9-8a3b-110d35542404</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29147a16-4111-4639-aab1-13ac8c6870df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8867a38e-d7ad-4c4b-82cb-999442f2763f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Brand - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7648434-f0d6-4336-bd56-ae2ab48fdf7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a356d0a0-7ea2-44e5-93c6-e16eb6b960fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Brand - With cancel create</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3790219-8f41-4ba9-9820-6671b7359cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b433263-63d5-4553-b035-6d1dcfbcd7d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6735f97d-ef93-46b1-b35f-6486094a2d98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3163f1-1164-4a0b-a4c8-eb4c96b65c1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Brand - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a370ebe1-cf1b-44fa-87e6-dca3ef309381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>872baf91-8ac8-4cf6-b0a6-e06623814491</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91e517c0-cbd5-42e8-933b-3064b0200489</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1d824b8-430c-4859-9ff1-8d64dc8e76ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bb2e162-414d-4621-b70c-453d5373e1b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>729bdc42-e69c-49de-80ef-4c41e7b68717</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30d14a3b-11c5-4275-b01b-626f286f9a26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b7407c9-c19d-46b9-8509-b55e5be2bf1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11625f75-0a67-4b75-8f96-aca0a6019188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d772aa28-223d-4305-8b4d-d9ccc580ae13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab1c38df-a715-4216-a784-03006e46b670</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With category empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>48b842d2-3ecb-4581-a612-97c610740fd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With model type value empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da3fe06-a95d-4da6-b4a7-7641eb8e3cdd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59e4a4c8-aac3-41e9-9e46-5b92cd2e5dba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Brand - With model type value over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3930e4ef-045a-4110-98dc-acce8d8d15de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55e3dfd8-f9c3-4de3-bb54-6bf713eadaf2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit - Brand</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>224997dc-fd33-43c0-b519-6ac29e25015d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf4fa3db-8775-476f-91d8-f78a686acca1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59c068d0-9094-4162-9958-0d65efbdfb8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18ed5b7a-f76f-4a1a-8e6e-44f63fd3f2e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31bf9896-9195-4ebe-8aa2-7dd175ce0d46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d267268-9926-4d6a-a68a-a9b078bfb5e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6477b8a2-db2f-4455-ab75-d8ab3a7e72a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02003ed6-f2c9-4fcc-bd81-76cea5063ce5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ebfe096-4c07-4715-ac5e-82259c52bb16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c210b3a8-42b1-4670-9641-2535418fa283</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b74dc623-e328-4a04-b56e-94ad08ea5d7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea7c1dad-5880-46ee-ba1d-2256fd8d61fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>030d9028-b43f-4ae6-8b13-4fcd4bce7172</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df85adc7-5bf1-4744-9a1d-432b7f781557</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With category empty - Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5674bdd-9233-47c9-a13d-71dc30b8e133</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a598c5d3-6924-4526-9ff5-be9220b0617d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With category empty - Uncheck</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddcda6b3-c6f6-419a-a9cb-0ef8e4f36c7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7c1d77c-a96f-4f0e-9948-6a8fc3b7b259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7aca1231-62c8-41ee-b0bb-ee213d41c19f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Brand - With model type value empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f74d1661-e56a-4504-b551-50eb533df499</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93974e08-cca5-4952-8668-304b1db5be4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create - Asset</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d5920f-6390-458a-af18-b6ae8d5e47b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9e668d1-aec8-49c9-bb4c-d73ebcdb9a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3598570-8e0c-49b3-aa20-06279ea4f631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed077a6-6b6e-46db-93ce-c73d069f8748</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>602b7f97-f010-465a-84e6-b42a4d1f34fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e42cfb28-10aa-4dd2-982e-698f8d6d688f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>421c530b-58e3-44f9-8ed7-cfdf0e48d51d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc4e734a-c7ce-4728-ac56-8c409235f943</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With TAG QR</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e644564-816b-4723-b167-586b81d7c6c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65f60810-407b-44f4-848a-fc6b190775f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f51261-68ea-413a-8166-a9ec450f6166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44403ce7-477c-481e-b91b-52684c84cd66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c72abf-5ec3-4ddb-a239-e1d702121c52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85453a1d-d1b6-4b6b-9596-89cb8a5d6b4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fedc802-101b-4735-b706-27227eb2e40e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b95e29b8-6286-4b2d-908b-59b3810adbbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With TAG RFID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3695e7b-5303-4f26-9636-3ca09fc2ee79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4db2784-6aae-49a9-910e-6b876aa8e030</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d7dd9d2-ea75-4b6d-8603-fc5444d4d568</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40853e35-cc4f-40a8-84ed-183bad62ac8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95c2775f-ac7e-4b6a-b824-baa04ff8dd1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c1fda1-9fbc-4932-bd8f-21c9c2c48272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a2b4e0b-8b99-4c3b-b711-78ae0c860105</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37fa27de-c155-4484-b867-56df03068b30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With TAG RFID and QR</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edfae722-6e54-4e32-abcb-145b7bcf666a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a78e4f5d-c41e-4d0d-a8e1-ba5039277fe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f575c6a-f53a-4898-a5aa-cdf9d5b25502</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba64a93-3412-4033-ba5c-83b7bcea0d69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d4471a1-aec6-4997-86c8-d5d921b8d907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c53c459-077b-4768-af1a-6bc76c49d131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6ac17c0-9c36-4664-821c-096452cc50a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1794b35-a2f7-4ec9-96ae-76e2a92b67da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With TAG and Addon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed0ea062-058c-4513-b703-1cbd41d7292f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cda82d90-453e-4318-b1fc-5a08f1208957</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcda38b3-dfb2-40ee-866f-56901affc5fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ab36fed-a542-43ca-8bfa-6a7834fef2f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5333981-6e5f-4da7-90c3-05fd54b3b997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80e4bf63-f3a5-410e-a23b-fbe68df2ab73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf4458c7-2bba-49c3-866c-78c852310053</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4e2e8bf-c927-41a2-8a42-567472ff916d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40edf56f-d7a5-4ddd-89b0-46710082788f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5080e33-c5d0-492f-87a9-e5a31c977732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d433632-a143-426f-9312-89e340389ae1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>584c6aa8-6b7d-40af-813b-25015d19506d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d21cff3c-7dd2-4c17-b753-6123d76b883f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fc644a-6d33-469a-90d0-2e9bd0daf466</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b8ee84a-f9b4-4609-acd3-043db4c2921d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99466677-8beb-4aa4-afee-1f2e1d541f87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4fbe035-0a9e-4342-b8b6-e8c4b9398a37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>090fa95c-493e-4082-a2cd-71047edb34c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>674e9b13-f728-4f19-beac-448cd5fbc446</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9d3340e-239c-4b54-bbb8-fe3209552671</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1c2d8c1-a196-495b-bec1-7015cc748d30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52a4a258-3573-4432-a72a-97aced43583c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f63a791f-d97e-47ad-bf87-3c0a966210bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With cancel create</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c268141e-5c7e-4d6f-8a3b-adcbb4f88c0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1889196a-7a5d-4492-94b0-be9ce5ac83f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88d73662-720c-4c07-9b31-c660e0b4ee0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba7e3b30-05ce-4ef8-b76d-d0604f59b80c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6287f486-507d-487b-8e68-e18167c1b2cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5fd5585-023a-40d5-ade5-42f269760b48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6221b7f0-37b9-4d79-911f-9a5451005edf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e5302e9-1d51-4e88-b84a-e5a74b1719c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Create Asset - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3deb442f-35a6-43e0-acd5-77191ea235b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e4ac305-a035-4594-9c6a-02e8db30924a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85345664-15cd-4946-8bbd-1dfc7c458045</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbe5ec1-8196-4a88-b474-784d47ca335e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e29b5d6-d350-4e0b-b9d7-13ee9f8159eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a244515-e0f6-438f-bb5a-cc728519e669</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07f426b7-4622-4b24-946c-9e27904c9054</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1972933-5a4d-497f-a0ef-b74a8f3a6200</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4d118323-6361-4aa6-bb5c-b99fa90d634f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fb621393-1145-4d07-9182-f01d05833837</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcaeae2d-a60d-403f-b191-37e783074811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3de2858-4fe9-448a-b730-2202b1671300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65809d50-3a88-4aa4-a2fc-63b1ed7e1593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>969451b6-bc47-42a8-bbcc-ff484954c3ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>392ff296-3998-4af6-a1f8-fc3b4f3c6cb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de15b6a1-6c2d-4cd4-88cf-a1ab45b4427e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c86741bf-f7cb-431e-9834-75dd474a7112</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With name special character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd48860-3fe3-4962-8905-582dc1289eec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a996e4c-af26-4194-8061-fc754bee324d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70b259f1-770a-4d04-8532-d7f3e90bb361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c74efa19-f502-40b6-87b0-1a2be4c746e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fb3bc6-e72c-434f-a126-ebb29bb061a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40224a29-e72e-41ea-97b7-099d55f9f33c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa8caf17-0714-49ba-9aca-dba9a173b9ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dc12289-a5ad-4be2-99fb-74202199a4d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With code over 4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b57fa50-fc62-45a2-8b9e-64ac5eebd2d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fc4ebda-c1e4-4a77-982f-2baf6845b532</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f604609-101e-4831-b31f-3355dcff956b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With code using special characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d8c9f5-09ee-4384-92e3-43a253c3a1bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0e1bae1-3438-415b-b8fa-e26b9bb27df1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With code already exists</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f416084-41a9-4423-902e-201314b31d02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d722f7-783c-4c97-af24-8f28a25f10c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f24fd042-9d7c-4cf5-9e4d-b1348b11f634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92172e2a-6f2e-4393-8658-8ef798fa2548</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7bbba70-806c-491f-a6d1-9f045d9dade7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b33af16-67d2-42d8-aedc-39dc728717ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0de08f3-210c-4890-806e-66792791d91f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With measurement empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fde999e-e6f1-4d5f-849d-3ccae66dc9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e21751-d8d0-4cfd-a866-b61ce4c65c5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36cc16ee-bd91-43b9-84f3-bef602a25495</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78bdbc78-ab66-4715-932b-9e5a90594105</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2dc9422-e16b-4d3e-bf14-5112c001a558</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With TAG empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c20f065-7676-4254-8c65-bace516d3752</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aa6bc58-15c3-412a-b5c6-19d8943cfa8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84d9af33-e613-486c-9a1e-8e9046d16b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdff7e9f-31b2-4d04-a38f-3f17883342df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c45714d-2237-4452-9bf5-797cf4423452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With Category empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>419f6652-34a0-41cb-afe9-863a96dbd6a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d73ca02-0732-48f8-a370-7bef1475a16e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cbf937c-c8b0-4775-851e-27b9e5622126</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515dcacf-3039-4bf1-96f4-17d6c7403ce4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb496197-29ce-4e4d-88e5-2d227800fd75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With Depreciation Group empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e3c3222-615d-4a32-a15b-7d7df08bff08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e68a5e35-654c-4a44-92a2-8e44bb790fea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9002ab2b-452d-4caf-a1a3-bbf08a309ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4851516d-5b65-4098-a5bc-96b32511681e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6797f324-65cb-4646-a6fa-7a8fc3ac689d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Create Asset - With Account Code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50dca6c4-8376-46fc-b9e7-e8b1d8c56534</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>638ed622-1a62-45e4-a6fd-81148d26e78b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ecca42b-5ba9-4073-8149-31c1884b0706</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d309b70-c285-4611-8160-4562e50390ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d48dd694-3088-4bbf-9832-8774f99040e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit - Asset</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ac92b2e-c9e0-4cb1-800b-81f4acacc29a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a66b4fa8-bf05-4aca-9752-f3df54533336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d67a98d2-893e-4fe6-acfe-5d6e218a3d41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db01a722-a5bd-4689-8f58-0e7b1a72122d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a0ab46b-4771-452c-b819-0f0678cde085</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b8c03f-6c62-453c-b821-639502140649</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>458b9459-1bcf-4051-8891-c49a529748a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189e2257-0117-453a-a1a7-a50fabbe4a0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0834c677-f057-40b2-bf8e-dbff63c90e2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be483440-c358-4310-b07c-3cc0ffaf39e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b754f1-91a6-4848-a670-39f5b117d20e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c3bc856-b48f-446b-9f94-82f4654ae070</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80919ab8-cfce-45b5-9666-451f43ff7fba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22180202-21c4-4a16-9e35-d1afc31401b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a3f5bd4-96dc-4e91-83aa-5cf9cf495e04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81a77efb-37ca-465d-afff-adb5f6c283ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit Asset - Change TAG Type to Non-TAG</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c880a0e9-52ac-4c21-88ec-0398fba37891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a46bfe47-47b2-44ec-b87f-e93ec44914b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f29df1ba-c432-4aca-aa67-a2c5547b9c3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cd9d9e6-2d50-4142-b6fc-71c7c40743cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit Asset - Change TAG Type to TAG</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba77b89-fcee-4aa1-9097-42fe5be1a581</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d51a36-78bc-4d12-9fc5-6f0354340932</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5b3c3f9-ffce-423f-917a-c18a921dc202</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6f5cd7f-e62f-4b6e-a6c9-0fd95bf8a2a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Edit Asset - Change Addon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f559d288-c2cd-424c-96a9-e59c1b20fb6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dadd79c9-b077-4de1-affa-d122b29b968f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>620e3b32-223f-466e-a7a5-e8787871a517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e3f04d0-7090-4b58-b3ce-fc0785c29372</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0996610a-9864-4d28-9e6c-bb9b4f368ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39fde63a-11dc-4699-b1ab-340400b19eb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>629e3ead-2ad6-4e75-bf2b-43c5bb08157c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a272969-b43e-4f3a-8737-51e5301edc75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ae28f6e-2010-4f04-922f-8dd75756fdff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>097b405b-9ad6-43f4-ac7a-69124f5791fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With name using special characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>758adfa5-c2bb-4cc4-831b-337398c96289</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0016a4f-c452-4877-88c2-1193e5b8e28b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a95a16e7-a680-4fea-97f6-34279e972db7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With code over 4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a080959b-4560-450d-8656-1936429edca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c68fef8-6b43-4e09-8de5-6988adbf5e8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841bdddc-5a22-45e8-bb1d-220762dc2986</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>525daefb-67a2-4814-b828-1a82fefe29e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With code using symbols</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f45679dd-49d2-4bc6-8efc-98a1e964167f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62facd6b-22a7-4a16-b638-0f7d7058cb79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>241894c1-df50-47be-b036-ce5d0f5683a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10bd1954-29cf-4a11-8808-ab8eb8e6e8a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Negative/Edit Asset - With code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c91b84-908e-4cba-a390-46f4bd9b6360</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4056b0c0-718b-4fda-ba39-362b75928b23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1be60fd0-2648-4945-8ca1-f7e4549c7727</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Update Asset - Set TAG Type to TAG</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d465a40a-639d-48e1-ae44-c64dd2878964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c8cca3c-6cb2-4782-8d33-77780298d1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ceb740-4df5-4e73-9dfa-fe2d58faa865</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e024509-5c0a-4a67-ab40-3ea4489f049c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Update Asset - Set TAG Type to TAG (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f6be53f-b8ae-46b2-bf45-e9f1cf57c983</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>701b099d-269a-40de-85f2-158e8bf54053</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19da880b-9a70-4b1c-95e5-442caa401e8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a6ded6d-c2c2-4f37-a3e1-ad3b70eedc7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Update Asset - With depreciation group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd0dda5-299d-4dac-9632-04200cc199c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>069e944f-41c3-4f2c-a404-7433346d9ac3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a9fe6e9-001e-4e27-9d65-65a9d82b6df5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c8e11b9-1dfa-48aa-bc5e-75ca779e4ba2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989caa6e-4205-4a7a-9155-573a52b22c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f47e411-b8e6-428b-8d2e-ff0b4d0bd15f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bffd75cc-f7ed-4ffe-bf0b-d0bb35804b34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Update Asset - With depreciation group (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d68f7bc2-364c-4a2b-b510-91463bf05f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e18e335-8a74-4bc6-9639-a639c0eed9d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8140655e-1eb5-4b35-b284-d2d0ce760b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0230078a-d996-4a74-a5a4-9e90d8da71e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21c8901b-30b8-49db-9ad2-0214911dd7c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73f43b73-0506-4bf9-8974-3a1ac1afde00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83e753f7-56a1-41ef-8262-432dbd7d854b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Asset</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>461417ed-4f3b-4985-931f-54bf298f2513</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>142764d2-857d-452d-bd82-d51b3a2ff567</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Asset With bulk action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5662127-8857-4731-bc8c-9ddd05cededd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19c92800-5c1e-4507-8814-15b6075cd36a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Brand</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7922abd5-59ce-425b-bc3e-00df2e40b536</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>324db403-a259-4f64-b94b-91c014ed75cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Brand With bulk action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c80c8447-75ea-439e-90d1-5a3860a994aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c694985-ceea-4a9e-b401-fb21b2367bcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Measurement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d854b1a-0048-4619-9156-38acc3a5d75a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d71531ff-e987-4e88-9fcd-af7a929799bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Asset/Positive/Delete - Measurement With bulk action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1bec600-7fca-49a8-a548-2696aec6d761</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
