<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Category - Create, Edit, Delete Category and Sub Category</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>af3961dc-d154-4d40-ae24-ab0ef2ce3230</testSuiteGuid>
   <testCaseLink>
      <guid>9b51b06b-c9eb-4efd-a104-8b6bfa6863b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create - Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5194f43-d3f2-4e43-ad93-d8e968b3bb30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a6ada9-6713-495d-a8a4-724abb9829c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d193a99-8e52-4149-843e-c27997c0f8fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Category - With category name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da02aba-18d6-4ce5-9e1e-877c506ceb14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>473fa92f-8b30-48d1-9aca-274923a50e9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Category - With category name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8729156d-72a9-4c8e-bc74-490be2b08e5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Category - With category name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ff665cbd-db54-49a6-b6ba-596ef3306e94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Category - With code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49ef9530-c5cd-4065-8228-7220468860a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb095a78-8b97-4417-af76-1532015511b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Category - With code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5f545412-bf14-4918-9587-abadd689c62b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Category - Cancel - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8fc79d2b-1adf-4edd-a850-65603b5e53b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Category - With clear field reset</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c617ca8f-7a5a-45b5-af17-c6fc04c923ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Category - With stay in form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12935bb2-52fc-498b-8984-a1d2978ee752</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bb930ed-8687-4cac-b929-04a66f9224c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c94c520e-41ae-4370-bcf4-96426aa5d679</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create - Sub Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad216ec6-1cff-4327-ba6c-6356df5b6e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51f924a7-6bda-4706-b5bd-d5ad2264f0c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2092760d-be7a-4d8f-922c-fce7f615f994</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1808150f-a631-4328-abe5-7221cb1f48b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Sub Category - With category name already exist - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9368f8-4fc0-4f29-9904-2bc854156aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bd23492-8331-45ad-b164-42e6878e9c08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53e3c871-c9cd-4250-be5a-07bbdb371815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Sub Category - With category name empty - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad4ae509-e1a8-472c-ae12-953f2d324828</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1e1f08a-bad5-456c-84be-3f9d6c0c58ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Sub Category - With category name over 30 - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7627d6fd-cfc4-4453-bcfa-62793aedfe9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42cf5deb-7c63-4f72-9af8-4676db442bcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Sub Category - With code already exist - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccb80e69-5b29-49e4-b5a5-3fc3c21ea31c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a5ec56e-f3bd-471b-86d5-1e3f2a3b09d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Create Sub Category - With code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a13f8b8-ce50-435c-a983-dce191b7c1bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b69a9797-98c7-4c0a-a815-75a0b3905890</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Sub Category - Cancel - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5536fd07-4512-4f91-8351-7496c3a0f8d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0de7d0e-c88e-4f4f-abf5-cc247737439c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Sub Category - With clear field reset - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1109a11f-d557-49cf-899f-7ef72520b3ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53d6e784-48dc-4d53-afb3-87214fd284d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create Sub Category - With stay in form - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01562196-72a8-4c91-b400-d557ceb73b23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cd5b52c-9f0f-4ecb-b97a-01a3e3ac2aff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a12e8b8b-07a2-4640-b457-11df25da12e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b80269f-8e6c-42c0-a836-3ccdb36069db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Create - Sub Category Level 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37c86894-5478-4ec3-b720-ebaa460e839c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4cbb59-0efa-4736-a642-e14636b6c750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee832ce-8127-4471-8d9a-6b4038d0c7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5a3bc2d-55b4-4b08-a31c-0ece8b819c43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86d6db49-3bfe-4493-ad55-9dc698104c76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>633d4113-84ac-4136-b6b3-ac5fa0b44809</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Edit - Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff0a0d48-5d01-44f0-be19-dee5b79d370b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbeeed5d-0645-4474-9e53-00f02ad000aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fead6cc9-cb2e-406d-881a-f78d8934737a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49734a1d-5dee-4120-aef7-762987c2549c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>220e11cb-1105-409e-8671-93bc448f71bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Edit Category - Cancel - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b94bf6e-b15c-4643-8586-3b382fd84cbe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7485b55d-28bc-4564-bfdf-edf26092c548</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Edit Category - With clear field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12b38dd0-442f-453f-9ce5-ec277dc6f3db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56389da6-0b46-418d-af8f-a4014eb4cf13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Category - With category name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c911891-da70-468a-97fe-d57d0b7977d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42fe62d8-b1a8-41f6-84b6-0de2bca32243</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Category - With category name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d7ac837-3399-47f2-8af0-60df8366ddb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6637dbb-afb0-41dd-a22c-3cf78b9b9d29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Category - With category name over 30</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9c6e874-2879-42fa-930e-6b9b9c1a1bcf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>137ff06b-06aa-49ef-8ec8-4f169be3e145</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Category - With code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4d13f02-3ad9-4d35-8462-644f66de3f8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3fa3f68-01fb-403a-b40f-5d35d9e2c2bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Category - With code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff2bcbe-8ce9-46c7-b836-7d9d6e098c98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e4cdf34-c0d2-4c23-9a9f-fcabd176579a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Edit - Sub Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>997e4947-643d-45cd-bd9e-30ba27cd3609</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c504a0-d8c8-44ed-a5fe-537a2f2cbdac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fc6886f-132d-460d-94ef-adc1a9c252c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36154f88-0251-49b1-a08c-b8d9f8d04fa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4521f83-7a70-4905-9271-b54134c48cac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69bcc81f-6157-4697-86c9-676d7863cd41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With category name already exist - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d06a820c-e6a9-4fc9-935f-54df73e2aa3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f06306dd-3955-4f03-a983-7c06c340439f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>383fec4e-21cb-4fa2-88c6-481b616fac70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With category name empty - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bc8f7c6-84fd-4fb4-9c1f-441aa0438ac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35e56ab4-4825-4ee0-8f11-d1dc8756a6f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f68409c1-992b-4fae-b9ea-4c7c27493c8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With category name over 30 - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd262c87-c8bb-4a94-818d-ca991ca38308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b16783d-72cf-4224-99c3-6c081e2d0c45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70a233ae-3040-4ff0-b73a-5bf1af08b164</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With code already exist - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d261107-9445-405d-9af1-542e0d17d902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f965f19-7cd2-47ab-ae97-2584e81fdd8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ebf5675-d928-4567-ac68-0e37032e0995</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With code empty - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bcfed24-9086-4383-a059-2a74687dfb9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0087d1ee-99b3-4b78-89a9-1c5f4e39a81f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e89714e-3f7e-4c2c-82d1-ce789c58622a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Negative/Edit Sub Category - With code already exist - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d261107-9445-405d-9af1-542e0d17d902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f965f19-7cd2-47ab-ae97-2584e81fdd8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4dcb5e6-b16b-4d08-8387-c65067825b44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Edit Sub Category - With clear field - Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b44476-acd4-4125-b916-5d4e3f6b1a8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3be4032f-3cba-4924-b329-0cc3cfb48af7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03f0caf6-d532-4f69-951e-aaa5945e9cf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Delete Category - With include sub category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4200058-b6d5-4e71-91c7-76d2a4faf785</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb4049a8-d996-4fe1-8258-be0650413505</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Delete - Sub Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44e36891-16e7-4396-a81f-c970143081dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3ecba39-bdfb-4ccf-9795-1ed36a316fba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33b6d7fa-8576-4d38-95e6-a47ac2c34b9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Delete Category - With exclude sub category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8b67114-ea11-49f5-91ec-a32de5d43a48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a7e6679-1aeb-4834-a2b8-d942a13009e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Category/Positive/Delete - Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4de5f4ba-d780-41d5-97ec-6e9a069b8c48</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
