<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>group test</description>
   <name>Group - Create, Edit, Delete Group and Subgroup Data (Without Asset)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>19e6fc25-d3e7-4e12-a164-7d905657c499</testSuiteGuid>
   <testCaseLink>
      <guid>31eb1b3c-4493-4cc0-9701-ace87023ddeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4368fda-097c-420a-a8ac-51bd9283cfce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a6ecb1-986c-45fd-bc01-b16eb0ef191e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e8b6970-9762-49eb-a10d-5f17a5878937</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Group - Stay on this form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>367989da-3816-4179-b5b9-d626b43cc327</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a2e3b4d-3758-4b32-a6bf-2f9378c55201</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Group - Clear Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>61bcb8fd-1aa7-4457-aab6-e1a13f23b35a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Group - Cancel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b6661560-15b9-48cc-beae-2059e0d27b7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>84c6d69b-ddfc-40b5-a201-b160741f73c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Code using symbols</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70af54c7-3555-498b-a955-dcf238864145</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Code over 4 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>649cd1d4-ff39-443c-8f28-cd4642fa9b3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eeb7cfa9-23f6-420d-8636-eb17e466f908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ecde0009-e35c-4598-8095-623fa5270659</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Group name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>822e5ba9-e1fc-45db-9d58-1ab25ad122fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Group name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>30bb7ff5-2272-4478-8df3-ad3726dd5aa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Group - With Group name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b89f93b5-bc4b-4201-a655-b5ce90434502</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d86d972-6f08-4c35-b7e1-d33e979ad45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>456fe47f-355a-449f-bcbd-9ff8c0ddc782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119e7ecb-c4b5-43e1-afb7-7f9cf885db30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5e53f3a-dde0-441a-b488-b4335eca8cc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Subgroup - Stay on This Form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb6ca76-1089-45aa-adf0-e5f09d944d25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>108e5313-0e62-46ae-99e9-3af757e40352</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac4dcc94-b02f-44a3-9a34-1e50ecc164c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Subgroup - Clear Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f690e126-d508-4cc9-9ded-0def553da162</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31e50f7a-a5b1-4f79-8f4e-8414483297eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Subgroup - Cancel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcdc7a79-6489-4663-adec-3f8d938f3253</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f250c174-99b6-40ce-8839-97b4ae890ddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe48dd11-02c5-4be3-b73e-e2911f5fd8ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>026c9d47-7a97-4077-b520-7210c2e4751b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b46764f-37e8-43e3-a029-6655019ec015</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d17213c-0c39-47d7-87ab-b2c4b317bb0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Code using symbols</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>073f5efe-ddde-4e33-94d8-33170262cf07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e479d512-9aec-4518-8feb-c959347f25ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Code over 4 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a18cab1-8c49-46ad-917c-d069188dfbae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfb17668-7acc-47d7-92ee-a46b3b254b5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>371ba563-9ce8-4d20-aefa-ab5249cff783</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Group name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25058bbc-ab58-455a-8f30-de615bc9a0cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b79a114f-2e2f-45a5-944c-bf674ba1273c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Group name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ce7e6ae-ed1b-4fa9-959c-c74a079ef740</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fedc4c32-de2a-4e64-92d1-527bfefdce33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Create Subgroup - With Group name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10db2403-e331-4ace-a52f-ce03871556cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b889f9d6-18f2-491f-8792-1823330f89c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - New Subgroup level 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a7bf2c-a71e-4940-8bfd-ad1fe5e3b35f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9313c3c1-baa8-42fa-8533-ea505b35cf15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05888b17-f7b7-45a2-b9ec-0b6efc4299f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4102feb-b1da-4b4f-9f53-d523d0aa536e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf4f3ba-ed6c-4c6e-a8a3-effc66a01ce2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e81f0806-ec67-4c81-a619-44d9346bc8ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72f66176-35a5-45cc-8df2-9beed8ad4f8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - Disposable Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f1fdcd1-28fd-42c9-a46b-5986b0686aba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c3a264-fc27-4feb-8549-2be31dc69ef5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a933562-fcbc-4884-a3b9-4e2b07ea5681</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Create - Disposable Subgroup level 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1367981-c231-408d-84a8-ff5668118621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1be413ce-8c51-46aa-aa94-5ab49b71b972</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed97ddd6-e7e9-46b2-a6b1-1f533cf0bdbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e57107b8-6ebb-4c40-a6c1-ee387b763428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Check - Disposable Group Icons</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a9775db-f531-42ff-be85-373280da7269</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36046210-d3d5-4501-8e77-a938c0c73189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94f944e-3931-421b-b6c6-394644f27fd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aeff6f83-271f-495c-a236-a4415bd22f5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b78892d9-0af3-47a4-b506-717eac1c3d59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27be775f-f89f-46a6-95a5-9e24ef6393f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9941122-6d8c-424d-83dc-03863cdfb746</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bdbbc9c-1be7-4835-a742-a973ad92b080</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5df45cb4-31f9-4772-8851-485a6ed7e56b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group - Cancel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3ab7a2-d2c4-4e30-9469-312113e996ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d35a195-8a94-4f30-a324-9497b887c226</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Group name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a123f84-f069-4d7e-aad9-6472dfbda27e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>851d6187-34d1-4280-b859-9f43a6a9af69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Group name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1463f4cb-01c4-465b-ac1e-ebe1ae6e2a63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1397393a-04f5-41ce-aec8-cae2471abc4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group - Click Clear Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cd5d916-47ab-4510-ae95-2bf6e70aee82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a89e1105-8953-4123-857a-6c3486697cd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a8b7b3e-3b67-46a5-9337-c4acb63128d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04f806b7-765f-465d-8775-887116019714</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f78cf2dc-be12-44cd-834b-8656259c7c95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae9ca86a-8459-44a3-89a5-18ac3e739ea6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Code using symbols</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed6fd240-95f6-4360-9428-413097f9925b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84647752-0ba6-4f81-bd10-36720ce8ebbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Code over 4 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22def03a-7126-41d6-a8c1-9615d0eabf8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a5b8c1-fa39-41ca-849d-3991edbc7b8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed19689e-5dc4-4a75-9fd0-d3f140879082</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Group - With Group name already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9be2d66a-f554-4c8e-8459-3e1a7f92e42c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc2a1dcd-9ec5-4d38-94b0-960ae5b569db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3486decb-7044-437b-8ed3-74c61120b9aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2370b4-2141-42a6-809f-c817eb10cead</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f1f03d3-2f14-4c07-8a53-0a2d180b8e7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb9762a4-9cfc-4063-9b1c-eaaf0f5af020</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70395723-f25e-4db5-b9aa-06143481b023</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group - Check Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bdbbdd4-20e4-4cc2-bb40-1686330a6917</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bb97182-08d4-4eba-b581-23b0455afe7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group - Uncheck Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f38913f3-296a-4fad-bc94-5d9b76a095ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d76b3020-fb3d-4d3c-8fb2-fe30e4f5d3a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8743462d-7baf-46b6-bfd9-179f79914ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0af00b00-9a79-4d4b-86ab-3ea34f1793d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e144977-e9b6-46bc-8d89-c0b54d3648cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3db8f5a-c52e-44fa-93d0-0f6128c29efa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b7c80bb-4dc8-4262-8ed5-36d1641fefc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39f3508e-1535-4f06-8a97-3e04c5a55869</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup - Uncheck Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c65e165-fa5f-45ff-aa00-da2247a474d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edfb9697-0516-4981-9727-4d198dc40887</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6386d2f2-1a7e-4c08-99f8-62cd8ca462dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup - Check Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6164e2d5-7edf-463c-b7d6-1e94afc348a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9de70646-6251-43d9-bf8c-76fbe89b3742</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7142ae4-aad5-42ed-8a4f-e9171a263a08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup - Click Clear Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd270448-ffbb-41dc-91c8-93fa2505595e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>902ed94f-c29f-41d2-af1f-5f089ba4abd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed53d764-16ec-470d-9814-a36fc8303725</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Code already exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1a0dc0e-7c11-44ec-aa0f-0d6206d6eb6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69821d92-284c-4f30-a9e7-454bc0a6bbb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d958e8d-1dff-473e-86cd-54ffe4eaa734</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Code empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9489db95-ae46-4a92-a98d-e66ff6d86114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40f9421-5e17-45d8-8ba0-77064f88d3e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>056ad05a-0fd7-46e7-b06d-a3be4146c770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Code over 4 characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f14d91d5-1731-4f1d-821c-08ee0bb570fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d8761f2-ca1a-4976-b4af-27eaf3526c04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42c73e84-18f5-4c2a-b9da-5da205235ba4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f21d0f8-f738-40eb-b016-f9219bce4392</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Code using symbols</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eabed40f-8600-4d52-b317-66888c6454b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>651b11b5-2321-4fc8-85f5-ee9e5b5c2e3f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef098778-5f21-45de-802a-04d74174fde7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Group name empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae7ca470-3547-4f81-9f1b-d946e15cae5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be1e9855-02f6-42d3-bc46-339e4c94b760</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4728825-6f0e-4243-a874-622584351438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Negative/Edit Subgroup - With Group name over 30 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cc8d520-a645-44c4-ad0c-bc904fd4efa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8202c4fb-bbda-4b29-8a01-5f25419c989b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7207e99d-b676-4b6f-94f9-68800726d092</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group Disposal Policy Activated (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>19ea360d-abc4-4ff2-9912-c3ec61b7da34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group Disposal Policy Inactivated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd20ae42-0ebd-452b-b51a-d44b5053e32d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83b9e9fb-0276-4173-ab61-440a3d44c323</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group Disposal Policy Inactivated (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fb66d07a-723d-4424-b96d-dd0762f76c28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Group Disposal Policy Activated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6234d0e4-875e-4840-af9d-4fa24eb52e0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a28299f3-d6a5-40b8-b4a3-25aca09f98d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup Disposal Policy Inactivated (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>39eeca18-e26f-49f2-8edb-823636442b09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup Disposal Policy Activated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9343b5a6-cf56-40ed-8128-d14e8da3820b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup Disposal Policy Inactivated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8f90b295-786f-4366-99b4-351b07b19d51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Edit - Subgroup Disposal Policy Activated (Bulk Action)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>786ef325-4ac2-4d2c-ae9e-f79bdad7d745</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Delete - Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8baa150d-aa9d-4542-a1d3-61c642f1fc44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75cb8bde-076e-415d-9c82-54a3fccda6f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>542968b5-05ce-4c5a-b5da-fb354e72f771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Delete - Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>676ba831-9693-422f-8c9e-9895a1258c9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>288fffaa-e986-47ef-a61b-de86e37cf842</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Delete - Disposable Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c65acb81-1ebd-4ae4-b4e9-1f6783ef556f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e6114e9-eea2-4ca8-8025-2d64c7c33d0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Delete - Group exclude Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0124f5d2-274c-4c7a-9d8e-7ad96a5d9846</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69d293e4-a204-42a3-b0aa-03efc9638d0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Groups/Positive/Delete - Group include Subgroup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d89276ff-2471-4bf8-aee2-f6e4c8dc4254</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
