<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Settings - General</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fe3292e8-99c9-4106-8ef6-f183091ee08c</testSuiteGuid>
   <testCaseLink>
      <guid>e09950e1-5ba1-4de4-96a0-4874bc286e46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set Inactive - Custom Asset ID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>29a654d7-f525-4a8d-8321-5763079ef06d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set Active - Custom Asset ID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c98be8-1ae9-4ea2-b7c5-da53c02b3963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06d048d0-a965-49ed-81b7-e8cfc96dc868</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7908da01-d9c8-492c-9014-b1b9d11cafb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Edit - Custom Asset ID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93614423-fa7b-425b-a6aa-5c17dc6d9fe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be6b3888-7620-4f44-b1e3-5462dd468a8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f987450-d8be-4185-837b-3adccc7c58d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58312186-0b94-4dd3-8e92-43497dddb3a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95c12a55-cb2c-48f3-9351-d851831bdc35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Edit - Custom Asset ID Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>265aa6c8-8344-45e9-bd91-4edbeae7b4a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>575d85d7-bf33-46ad-90ac-0bde77d25449</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>533af143-d977-4f68-8936-d0391c943f6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Negative/Edit Custom Asset ID - With all data uncheck</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>75a6fabe-118e-4eef-acef-a1d3d11e16d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Negative/Edit Custom Asset ID - With Company initial empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>72cfbe0c-2e7f-404a-bcc0-77119b5d710d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set - Default Currency</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23d4d554-96f7-4a5d-b0c3-456dd6555dbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e586fa4e-2dd5-46a9-83ca-33b0da1a1eef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a02abb10-bbdb-413f-aec3-d5abc2cd2cff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set - Time Zone</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd9126d6-a761-42af-91c4-2d6f19c04cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaf79541-1442-402b-93f7-11e03a14b1ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fad7a03b-ccd2-4917-870f-8e4902b9bf0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set - Date Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>390e0463-870c-4c8f-8d9b-65966e963439</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>105c9041-b9dd-4a87-87df-6597e72cf544</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79638e84-9d97-4599-adf1-43a26de4b9d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set - Time Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>920e26cb-a2f0-401e-91fb-a50360cdd816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ff17cc-bb4b-406b-bb6a-40b6b881ab7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a5d5920-3b8f-4dc9-b4b3-ed0912b368ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set Active - Geolocation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bc9b5a57-a2f6-4840-9bb1-e90052b9c314</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - General/Positive/Set Inactive - Geolocation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
