<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Settings - Transaction</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e2363b3b-1152-4197-ad6d-fb149e621c72</testSuiteGuid>
   <testCaseLink>
      <guid>4ea7f11e-eb3c-46d9-bc89-fe1473050e23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Borrowing and Assignment - Max Borrowing Time</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b851f9dd-f749-4b8d-88cd-c14c085a4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f297e8ec-3dc1-4820-967b-c784a84f325b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>752e429b-0386-4190-8173-3b832f317cae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Borrowing and Assignment - Default Borrowing Time</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4f21514-b2e0-40ea-893e-262fa62528fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c71ebaac-d171-4ef0-9960-f94b1bbe4509</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e123bd08-d4df-46b0-9976-f81dd52350f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Borrowing and Assignment - Confirmation Email Timeout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d1bfe76-a52c-4c82-b98a-74d6e8129fda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e6a3a31-4d78-4fb2-863a-4bbd22a3e13a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Borrowing and Assignment - Transaction Timeout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9825541c-4e06-4755-ab18-3dac440f59c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d861db9d-827e-40c9-9fce-c2ffba81901a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51999a10-c63f-4816-adfb-8b9a5f919df7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Transfer - Asset Control to Missing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8faeeacf-c5f6-4d45-a90a-915664cf3fe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76c876f5-fc34-4f83-a5d4-d41c9af2865f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0819613-49f5-41c4-a0a6-998ae86c4bd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Transfer - Transaction Timeout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1588b915-64a3-4992-b0b3-c53513e7282a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4342f29-bb78-4a59-a15a-84958b37d411</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>535f57bb-3937-407a-a7c2-2eefdfd346f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Disposal - Transaction Timeout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c47b22ba-149f-4f75-9305-8764edd42fb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6231bcd-f3a0-4439-bb2d-424cffff06a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11345b7f-6fde-4607-b120-357507660593</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Settings/Submodule - Transaction/Positive/Set Audit - Max Grace Period</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7068620d-d236-4c29-9946-73b79061bb3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aefe0cc1-ceac-4dc0-89e6-17b611fd16ad</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
