<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toast - Success</name>
   <tag></tag>
   <elementGuidId>f133c3c1-4be5-4ada-b373-ad5ec44519e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), 'Success') or contains(., 'Success')) and @data-pc-section = 'detail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c59cc411-727b-455c-95a7-bf8b678dee2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success</value>
      <webElementGuid>c273ed9c-cc6d-4cf1-a019-63b0e14e4820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>5cbddb90-a279-467a-b5c6-590cd33452d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
