<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validator Message - Must Pick</name>
   <tag></tag>
   <elementGuidId>808810a2-ff6e-43d2-8ca6-0ae1805b60c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='undefinederror']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#undefinederror</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You must pick&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>0fb2177f-e96e-4ad1-9ae7-b10ad17e850f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!mt-0 text-danger-500 dark:text-danger-500 text-xs font-light</value>
      <webElementGuid>3a5b101b-04be-4a9a-a1b9-8b79ec297d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>validator-message</value>
      <webElementGuid>e9902a3a-7ae6-4eb2-abaa-af11cfacb279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefinederror</value>
      <webElementGuid>f6b430a2-85b7-476c-834f-19d9584d39df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You must pick </value>
      <webElementGuid>5ee460f8-ac3e-4322-816d-d7ae0199c238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefinederror&quot;)</value>
      <webElementGuid>4a342203-1216-4d5a-9d25-de0aeb60ac44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='undefinederror']</value>
      <webElementGuid>b7ba72a5-54f7-4632-a965-fb39407f6d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::small[1]</value>
      <webElementGuid>95d03138-1c8a-4ebe-8932-e63d4b3c171a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required?'])[1]/preceding::small[1]</value>
      <webElementGuid>f8937c59-038d-4657-82fe-86d9f8b6b989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::small[1]</value>
      <webElementGuid>7f4ff23e-9360-41b4-b2bb-5e39565bcaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You must pick']/parent::*</value>
      <webElementGuid>39e6ba14-1976-44ea-9bd9-9cc610aa8034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div[2]/small</value>
      <webElementGuid>03b62321-a4ee-4f63-b548-d2f115047d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'undefinederror' and (text() = 'You must pick ' or . = 'You must pick ')]</value>
      <webElementGuid>b527e3cd-150d-4cf1-a8ce-6e12455c309a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
