<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - OTP 5</name>
   <tag></tag>
   <elementGuidId>23192a18-a4f3-47c5-9ee5-b2022b8239ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-auth']//input[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(5)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce33c0a5-5abf-4c66-a47e-565a0b5026c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2503b71e-0b43-4de7-a008-36980903071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leading-none font-medium text-center m-0 p-3 w-[42px] h-[42px] text-base rounded-md text-general-800 dark:text-general-800 placeholder:text-surface-400 dark:placeholder:text-surface-500 bg-white dark:bg-white border border-general-200 dark:border-general-200 focus:outline-none focus:outline-offset-0 appearance-none transition-colors duration-200</value>
      <webElementGuid>c3afd598-0064-46da-bdce-64c8c6aba98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c649b39-5458-4ccb-9dc8-f31665cb5bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>ts-inputtext</value>
      <webElementGuid>8a85c269-2e94-4210-a045-384a50240a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08af147a-d0f0-44e2-b275-ed275eb2b055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-extend</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>c8a99561-82bc-474f-82e0-e31bd28653e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>b8ad80f6-4092-41fa-a62e-394293f300ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@tagsamurai/ts-mfe-auth&quot;)/div[@class=&quot;single-spa-container&quot;]/div[@class=&quot;h-screen p-6 bg-primary-50&quot;]/div[@class=&quot;h-full flex flex-col gap-6 py-[47.5px] px-6 bg-white&quot;]/div[@class=&quot;grid grid-cols-2 items-center gap-12 w-full h-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-[420px] mx-auto&quot;]/div[1]/div[@class=&quot;flex flex-col gap-7&quot;]/div[@class=&quot;flex flex-col gap-3 w-full&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[3]/div[@class=&quot;flex gap-2&quot;]/div[@class=&quot;flex items-center gap-[6px]&quot;]/input[@class=&quot;leading-none font-medium text-center m-0 p-3 w-[42px] h-[42px] text-base rounded-md text-general-800 dark:text-general-800 placeholder:text-surface-400 dark:placeholder:text-surface-500 bg-white dark:bg-white border border-general-200 dark:border-general-200 focus:outline-none focus:outline-offset-0 appearance-none transition-colors duration-200&quot;]</value>
      <webElementGuid>4cfa0b5c-8070-4bdf-811c-1e1aa746900f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>c5176ba5-ab3b-41cb-ac6c-8814fc8a7547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-auth']/div/div/div/div/div/div/div/div/div/div[2]/div[3]/div/div/input[5]</value>
      <webElementGuid>1bf1b0d9-41ca-4271-827b-c98628bf4b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>54b64df1-993e-44e5-8bd8-133d651885d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>42a53694-d9bf-499f-86b1-9a53fe46808d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
