<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action - Approval</name>
   <tag></tag>
   <elementGuidId>41899263-a13c-48cc-b3b8-a2e57a472d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d9467ac3-0f6e-4d93-a38e-fb0c9b0480b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Approval</value>
      <webElementGuid>d948e418-d9f2-4752-a2f5-b6ea02bc8585</webElementGuid>
   </webElementProperties>
</WebElementEntity>
