<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative Edit Specific Data in Table Row</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>87f26a9b-107f-442b-963d-607860c822fd</testSuiteGuid>
   <testCaseLink>
      <guid>759752d6-6c1b-494e-8ea4-09edff3aef28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Auth/Positive/Login User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4445b2af-5c75-4018-a64b-3f52fdf0bd2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Click - Fixed Asset Button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>86b09fa0-55bf-4e85-86cd-6881fb014a8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Click Sidebar Menu - Import</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>eb682771-40f8-4657-893b-e00f7f963e64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Group Data, Group Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ef175ef-04dc-47e6-b435-abe4f4d56d0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f76120ce-97bb-4f0d-9b53-0c8ca8f85e51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Group Data, Disposal Policy Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9540d2b-bd25-4f1b-b7c0-5616aaab56a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b9dcb45-2e03-4f19-b87e-cc7684409e29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Group Data, Disposal Policy Wrong Value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76cf34ef-7355-4d48-9784-bcc3e2dd6709</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5475b10c-82c8-4b2b-b6b3-a84bcfdd22db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Group Data, Group Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a95b3c5-9ae9-47d7-90b0-af93852b179b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>050180da-a964-4499-b234-2aa97fafb5ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Group Data, Group Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>041cd3d4-cbaa-4e13-b248-7aece289a814</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>776e468c-688c-4fc2-a3ea-91f247d47b64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Category Data, Category Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deb5e88a-7160-4b43-bbcb-ce91887c1b02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f094905b-3543-406f-8bac-bd682c282e62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Category Data, Category Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6cf2019-e3de-4a67-8e49-4998999e3d02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3320f68-bc61-44f7-a1ef-5553ddbf3e5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Category Data, Category Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4bce51d-7892-4b85-aa8c-bd120eb1fc89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0fc028d-b520-4a9a-9bf0-0b3e36e70544</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Access Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12f3ff56-cb67-4c82-9bf3-0d5ea42279a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2ca300c-ccbc-4c8e-9c51-2f489577206c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Access Wrong Value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8738585b-242e-4731-bf7b-f7dc2aabe8fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88d63d3b-2b4b-46cd-910f-80a34a69d526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Division Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61cc19bd-7093-4e8a-ba96-68b5a7afe789</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77aa9690-6d4e-4087-b8a9-c8c28bd7f3e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Division Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0c54c6f-59fa-4c19-b48a-27bcf238717f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1482ff11-506c-4b38-9dfe-a0c7f9eced1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Email Invalid Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bad6c63-c837-483f-ac93-57c2ed97523e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49023ff5-5d44-4df2-bbea-face072d41cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Email Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc38b8dd-f1cb-4b8f-8317-17fd1b54f6c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5e1eb47-9ff3-41a8-9440-e1d645788f52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Email Lebih dari 60 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b42eee-e157-46cd-a3de-33de8f37f80d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6abf310-a5a9-440a-a5d4-d0f76ae3a50f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Employee ID Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b22917-7d8a-483a-b30f-0deab79ff5eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ff72619-f1e4-4a06-894c-6170b528b50a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, First Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1225daaa-f6b4-4de3-b46a-a6fb65992917</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dc6367b-69c8-4226-8fcd-53a352d1e8d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, First Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11240dc2-305e-440d-bd2d-373cdf6038f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d579c9c8-d12f-4e3d-b96c-cd9b140f69a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Last Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7e769e4-8b3e-4e1f-9c83-fe8b18b79eae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5d69147-0873-4959-b110-04a092b1e620</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Last Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59b50bef-2573-46e2-ae31-8bc05ba99c87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c3b370d-82f6-4d2b-a516-857509c22256</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Phone Invalid Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5379fc6b-c3df-4b22-a775-cda95493fc48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f690ab8-de9d-4271-9cb9-5176199af7dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Phone Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa41b205-5f0e-4f75-b31c-1fd8cc41db47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8646c3fb-56b0-433c-b05f-796ea208f2b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - User Data, Position Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd45adbe-0130-4682-89ec-c73995062e25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f4a8219-24aa-45cd-b91d-3cb5010b0533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Asset Name Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08d9b65e-b5d0-4cc9-acfd-3e51a9bc7e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fd683e2-d0fc-4f6f-8fe6-908ea184cae3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Asset Name Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae9514ff-1e88-4003-b33e-80bef9310a33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>79d8cad2-51bd-426a-9ce4-d8f4e902bd21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Asset Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f294846-a7c8-435f-99a3-90d1710f2efb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82ebc1fd-e259-4b0c-8c14-ecd688078b05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Asset Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08b08c41-618a-44c6-8bd3-170e9123ad74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0eb4f11-a0d3-48f6-aead-ee6f12d480a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Category Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b17140-4adf-46b9-88b7-e35afbd2ec43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3ecb438-ab6e-408e-8ace-f8ca6070e910</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Category Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f3d8997-ba33-4c7b-9044-1cda0443b638</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83f34617-aa2b-4236-8df2-eca232371581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Category Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95a76f91-03cc-4f6e-940b-c79d301894a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52acaf32-1ba4-4c84-b40b-45b13339c7a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Category Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87519dd2-12b5-434b-8fbc-70e84402a241</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>526637b5-266a-4b43-adf2-512b0c1efffb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Measurement Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bdc3eb-4c30-4056-ab18-4a56cd855169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>585cdc69-3660-4ab9-9eca-607a501b2ad2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Asset Name Data, Measurement Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e496be15-32aa-41fe-8615-39a7ceb7439d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ee1d0c2-ad42-47b5-af25-bc6e61af5bdb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Measurement Data, Unit of Measurement Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c30d75-ea5c-4d1e-81b5-e4a6b781dd07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d82b25e1-90b9-4abd-84b9-29941930d2c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Measurement Data, Unit of Measurement Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98ae8e64-fe7b-4ced-ba1a-dd2add7ac2ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfc36687-afd7-489d-a702-817bfb2597f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Brand Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f22c9855-6684-4f86-b4e5-c37eff790b3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c356dc51-c884-401c-82d2-c6c0019ae98e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Brand Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e287e68a-80c5-4267-bb38-98baf976a3fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e56e0a9f-988b-4559-8a2f-7a96dc07c27c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Category Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0102daac-9383-41e2-b1e9-0f214cfe5de8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53b71ee9-e9d6-4782-9ba2-4bc45758ad28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Category Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd9a3227-900a-4bf4-b53d-06ed7b6431b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7037927e-0091-4df7-a6ca-5eba24fcbd83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Category Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee49de7-45a1-47c8-8c88-10632ce0e9c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>883bcf15-fd6d-4abe-b5e3-06f0e0288724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, Category Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>927892f0-06b3-45aa-bac0-21f6a854a0cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ae32fc0-fef6-4893-9273-06a0b81d9770</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Brand Data, ModelType Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>226c309e-8554-4509-ae39-9da1a61770dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fc219be-341f-462e-a2c4-cd5f059991a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Category Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>976f9fa4-fe40-4a4c-8e9b-a0bb9fd7cff1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e39abb7-648a-42f5-92af-27fc81fc21f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Category Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9588db53-8111-442a-899c-2a9c422b7d9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4eaf5f01-5e1e-4694-80f1-1dadc198034d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Category Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5101dd32-3249-4f26-8442-852952c5548e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76b32288-0686-4954-ac5e-5ad4caa95f9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Category Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfa51ff-1c4f-4544-bee6-d990a000bf05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93a233a1-edd8-4b8d-ab61-77d47cf65f77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Data Type Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20ee9952-33fb-4d4c-9ffc-de1c917dc28b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1ce49e3-6910-4ec6-9608-9c132842cf08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Data Type Wrong Value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8987958-d523-4903-b991-939e1b58a4dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cdcd4a5e-d487-4dff-860e-915487da014f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Field Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c604fb33-68a3-4fb9-8add-6c4d5ce27c4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f13f1b7-0f57-4c52-bfb4-9353c87186fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Field Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecbda9d1-251c-4d9d-8c9f-fe0ad294eec8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>612a51e1-3294-488e-ad3c-8d97b83ba44b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Required Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21a71a5-793b-4927-9159-a658ef1de6ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8060d579-ab0e-4149-9926-5d9b2090fd19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Required Wrong Value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b0d2a4a-2317-4a93-a2fc-b2e4072a69fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37a44bc7-b6b8-486e-816f-3311d1ab6c2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Type Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab733753-1c95-4cd8-b4c0-26a68eb0f88b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1656424-d0f3-4788-98c2-13577a7bb6bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Type Wrong Value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72221713-dd2f-48a1-9dfc-f8ac05968802</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3987d55b-70c3-4b56-840c-0a9f9e2d9915</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Custom Field Data, Value Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e715eee2-0f4f-4765-8f9d-39d9543eb3ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88561728-d039-41af-9464-36686d9ee07e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Account Code Data, Account Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48b0abf9-c6cb-41d4-8ea6-84ab0a857e94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e1538ae-8f68-4d19-a056-464345e24445</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Account Code Data, Account Code Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21aa76de-3152-4a7e-8137-99bf1ef4b0ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b447c821-99cb-4421-992a-bd34eb6b91cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Account Code Data, Account Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c84376-c6af-461b-8fde-766b4988d6de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34a45d38-f32c-4e74-886e-ac36b9dba1c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Account Code Data, Account Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>477d85cd-996e-41ab-acfc-b79647e0050e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>511b2237-7e66-408c-8205-72e282fd4c44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Depreciation Group Data, Tangible Asset Group Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9b9f1eb-0fa6-4515-8030-5eeb681d9600</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20a75eb7-b02c-45e3-95b0-18b0f79aafb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Depreciation Group Data, Tangible Asset Group Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d7fc1b-e28c-489b-b1f0-bd1ec55dcf4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c45382c1-a5d4-426d-8b0a-e88d5852995c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Depreciation Group Data, Useful Life Diisi 0</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4de9a9f4-fa12-4e11-82e9-ad523303ca40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d80def14-b17e-4d2a-b4e0-96141d1e329f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Depreciation Group Data, Useful Life Group Diisi Huruf</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b75fb438-0264-4388-9e52-f46c4bba9946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>829bf5a0-e7af-4a30-b436-33a49de6b2c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Depreciation Group Data, Useful Life Group Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ad28380-86c4-4aa3-a428-6ce64cff8b33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21958f22-5c2f-4fe8-9f48-4f0ab3b7342f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Asset Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04b372d6-ce07-49ca-b397-c66b0220f003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a196101-8768-4f1a-8f42-8b813f528004</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Asset Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1beed00e-86aa-43d5-8b02-55a58886c224</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82645a99-3ccb-494e-8432-0bc43a32984f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Brand Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4353415-06c8-4409-8457-6b074db06f5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1cc6f356-959f-48a2-81ea-dc5d4ece3883</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Brand Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7b870a6-9f6b-4955-a4b3-a39b7f93fea9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de4cd75e-eddb-4757-b24d-570d63db53bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Category Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab4c5024-ea1d-4abf-806e-5e1838c79c13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f93f323-69a7-41a9-8287-174ae7b90811</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Category Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e92597-c528-4a4d-8346-f29da8a8efe1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04053f30-331b-4e55-8aaa-3e1ff0b437a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Category Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b511b1-98ac-4317-9954-a58d77bb74f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e10cd3f9-fd29-46e4-8b70-37f8bb57717a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Category Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0baaad-a076-4ea2-8eb6-3c4010b23c84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b05f4fe7-b1bb-497d-aa24-fc507a01ad39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Currency Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07bcb4a5-9d05-4ca2-9648-a9d48758dd82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bce1be9-03b1-4964-89d8-39fec8f6f887</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Group Code Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a566035-129e-4ab3-b669-f8d581ea9819</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>866b63f2-072d-4fca-84ee-725472db1d33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Group Code Lebih dari 4 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e6d8a5-e84c-4136-8b32-5ea6ea1fe293</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>132a52a0-7bc6-44d1-be50-94a25b9b484f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Group Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a15c1d3-3c6d-4b42-a5d9-d84213271252</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a091da44-78a5-4bc1-88bb-767bc38e67d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Group Name Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>038eb6d6-a27e-45a3-8f4d-d513ac5422f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5788b146-909b-420a-b963-2ccdba116868</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Measurement Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>699d7c9d-2500-4ae8-b5a2-521b86803571</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>255dca15-0fbf-4799-9330-e16c5b168449</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Measurement Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e67d944d-f76e-4634-9e4a-4b8fecc93b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2fc6ee9-e84c-4064-bdc8-8d579ad36ca2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, ModelType Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c756aff-0cdc-4e95-9c28-5dacecb88fe8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e6b521c-d512-4cc8-879c-3a759bf7e723</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Cost Diisi 0</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c9453b3-766e-4c44-a1ac-246f4cb8215d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f12658bf-25e4-4b5f-9f94-414e905524a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Cost Diisi Huruf</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6614965-25ac-418a-97d2-48f799b00b59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f7beab7-af87-47bb-84c5-6bd324f6d614</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Cost Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2c9fbe5-f438-45d4-bd51-123e17064b77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82213390-2e96-47ed-84f1-06bcc7d0134e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Date Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27da7649-fe95-406a-9be0-b7d605cd87d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f03af29-9c2d-4cf3-afa0-5a41bc395bed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Date Salah Format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b98edd4a-e4bb-495b-8d1d-dbabf5f20817</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b36cc94-226f-41fb-bedd-58b6d2278c28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Purchase Date Tanggal Melewati Hari ini</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e456110-f199-464c-84e8-71c73ba01109</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f2aad58-d19a-465d-84af-a9c21acfa3ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Qty Diisi 0</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd1cd9d8-cf31-4cdd-ab1c-8a07a10f79ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d06a14a-40d9-4372-b1bf-7e12cb162b80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Qty Diisi Huruf</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccd40fa2-498a-4fcc-bfa9-ff3a6fbc3ec0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>589bcf08-08ad-4ce0-9c58-b80dafe87ec2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Qty Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47b1efe1-c46c-4547-a6b8-e4551724d423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e04d836b-7a58-49f0-8beb-f47d938aa55e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Tangible Asset Group Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7518bb8-e95f-408f-ad34-12a9017b6c47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cb8223a-2613-4474-b0cd-80ccf171b6eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Tangible Asset Group Lebih dari 30 Karakter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c8b2fa-1270-4630-b976-8e932ed34720</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b8a79d8-dcf7-48d0-820c-b40cc332d121</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Useful Life Diisi 0</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8618a03b-b564-401c-b711-21d6bf1abfc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9ceeeca-4731-4d8a-bd71-3aea02e96204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Useful Life Diisi Huruf</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed81b230-511a-4c66-9e15-29440c1dd236</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91b39bdc-5c62-40ad-bf37-e642e3ef8abc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Module - Import/Negatif/Edit - Fixed Asset Data, Useful Life Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f23da6f4-d623-4946-8c11-f447922bf296</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
