<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox - Select Spesific Group</name>
   <tag></tag>
   <elementGuidId>c0fa2a87-3a18-4d4d-b388-aafc35abf5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[28]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;Test Role&quot;i] >> internal:label=&quot;Not Selected&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9da580f9-4416-4f3f-b68b-afd25a426fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a69fa57b-9268-452c-b278-b382ff4f71cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input peer w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none border-2 border-surface-300 dark:border-surface-700 appareance-none cursor-pointer</value>
      <webElementGuid>6769edda-6da1-4842-b3d1-3f173881d970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f596391-1f7e-4e59-9b8b-c5755fa8d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1766458437669&quot;)/div[@class=&quot;overflow-auto&quot;]/ul[@class=&quot;m-0 p-0 list-none overflow-auto&quot;]/li[@class=&quot;p-[2px] rounded-md focus:outline-none focus:outline-offset-0&quot;]/ul[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/li[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/div[@class=&quot;flex items-center rounded-md p-1 text-surface-700 dark:text-surface-700 transition-shadow duration-200 cursor-pointer&quot;]/div[@class=&quot;relative inline-flex align-bottom w-4 h-4 mr-2 cursor-default select-none&quot;]/div[@class=&quot;flex items-center justify-center w-4 h-4 rounded border text-surface-600 border-surface-300 bg-surface-0 dark:border-surface-700 dark:bg-surface-900 peer-focus-visible:ring-2 peer-focus-visible:ring-primary-500 dark:peer-focus-visible:ring-primary-400 transition-colors duration-200&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-tristatecheckbox p-checkbox p-component relative w-4 h-4 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none border-2 border-surface-300 dark:border-surface-700 appareance-none cursor-pointer&quot;]</value>
      <webElementGuid>8c730813-1bdd-4fc0-b57d-57b4ece89044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[29]</value>
      <webElementGuid>a1003402-5fd2-4130-825f-cdd96be82be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1766458437669']/div/ul/li/ul/li[9]/div/div/div/label/div/input</value>
      <webElementGuid>ff16d6d0-201d-4b46-a3cb-a1c26485b3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/div/div/label/div/input</value>
      <webElementGuid>6778bd65-7c8b-4990-90fa-443a8d57f166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9813b333-b127-4dae-b887-35f4e04636e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
