<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox - Permission Create in Detail System Role</name>
   <tag></tag>
   <elementGuidId>48d4b08f-d346-4694-8231-9e0fdf2b90e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@data-pc-section='bodyrow'][.//span[text()='${userName}']]//td[@data-ts-column-field='permissions.create']//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84bffa24-d864-463f-8ef1-c8e8136ae8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>88780bfc-a809-443d-ac32-2ce580f95d3c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
