<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action - Titik tiga subgroup</name>
   <tag></tag>
   <elementGuidId>0ab7d475-8f7a-4b94-8aff-ba3608078f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(), 'Data-')]/following-sibling::button[@data-ts-section='tree-node-menu-toggler']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@data-ts-section = 'tree-node-menu-toggler']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=treeitem[name=&quot;aaaa&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc9dd387-6794-42eb-8f12-d6c012d93f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8d9da99-89d6-480d-9d55-55506601dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!w-4 !h-4 !min-w-4 p-0.5 !text-general-200 !dark:text-general-200 rounded-full relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] w-[26px] p-0 ring-inset rounded bg-transparent ring-transparent text-general-500 dark:text-white hover:bg-surface-300/20 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none</value>
      <webElementGuid>2c23c61f-46c4-4a71-949d-de19215c8933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ts-section</name>
      <type>Main</type>
      <value>tree-node-menu-toggler</value>
      <webElementGuid>8b95fecd-42b6-48ad-a31c-5714519882cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61d99b38-8eed-42ee-99b5-0f637c91c0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>91a4ab6c-e181-456b-80e0-262154ca53e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-severity</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>c0624c68-1805-43e3-b0d1-4a07bc4516df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-tooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e456acc-d19e-49fb-a4f2-9e6a30022509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>a6032f1a-51c3-48d7-a2fa-9c9b1fd64642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1733193519470&quot;)/div[@class=&quot;overflow-auto&quot;]/ul[@class=&quot;m-0 p-0 list-none overflow-auto&quot;]/li[@class=&quot;p-[2px] rounded-md focus:outline-none focus:outline-offset-0&quot;]/ul[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/li[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/ul[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/li[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/div[@class=&quot;flex items-center rounded-md p-1 text-surface-700 dark:text-surface-700 hover:bg-primary-50 dark:hover:bg-general-700 transition-shadow duration-200 cursor-pointer select-none cursor-pointer&quot;]/span[@class=&quot;inline-flex justify-between items-center gap-2 w-full text-xs font-medium text-general-800 dark:text-general-100 [&amp;_span]:dark:text-general-100&quot;]/button[@class=&quot;!w-4 !h-4 !min-w-4 p-0.5 !text-general-200 !dark:text-general-200 rounded-full relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] w-[26px] p-0 ring-inset rounded bg-transparent ring-transparent text-general-500 dark:text-white hover:bg-surface-300/20 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none&quot;]</value>
      <webElementGuid>986b2508-0f04-48c9-9366-a24148f55705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[33]</value>
      <webElementGuid>3f8e7e8e-a17d-4824-800e-cb79693cbd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1733193519470']/div/ul/li/ul/li/ul/li/div/span[2]/button</value>
      <webElementGuid>cc2d9dbf-d8e0-4c2b-b4ef-235679046941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aaaa'])[1]/following::button[1]</value>
      <webElementGuid>7f2bf9e7-7e3c-4af0-a233-73e44b3f4886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aab'])[1]/following::button[3]</value>
      <webElementGuid>367e630f-08f3-44e9-958a-ba8976e3dbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DisGroup 1'])[1]/preceding::button[2]</value>
      <webElementGuid>7d981d70-9fcd-4151-a423-62feeb2cc72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='grup maintenance rutin'])[1]/preceding::button[4]</value>
      <webElementGuid>be033946-1d3f-4bd3-8192-c2ab46b2b45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li/div/span[2]/button</value>
      <webElementGuid>2ca35e63-f356-430a-aa56-c3c07657dff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>66b23c4b-125d-4f06-bb2d-63d45584b3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
