<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chekbox - Select single</name>
   <tag></tag>
   <elementGuidId>31cebf5e-1aa2-4aac-8ff7-5cfbb90faca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings-group-settings-group']/div/table/tbody/tr[1]/td/span/label/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;settings-group-settings-group&quot;)/div[@class=&quot;relative rounded-lg rounded-br-none rounded-bl-none&quot;]/table[@class=&quot;w-full !border-separate !border-spacing-0 border !border-solid !border-general-100 !border-t-0 !border-l-0 !border-r-0 !rounded-lg&quot;]/tbody[@class=&quot;[&amp;_tr:last-of-type>td]:!border-b-0 [&amp;_tr:last-of-type>td:last-child]:!rounded-br-lg [&amp;_tr:last-of-type>td:first-child]:!rounded-bl-lg&quot;]/tr[@class=&quot;!text-general-800 dark:text-general-50 bg-transparent dark:bg-transparent focus:outline-none focus:outline-offset-0 transition duration-200 cursor-pointer&quot;]/td[@class=&quot;[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap transition duration-200&quot;]/span[@class=&quot;flex justify-center items-center&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-checkbox p-component relative w-4 h-4 shrink-0 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer&quot;][count(. | //*[@type = 'checkbox']) = count(//*[@type = 'checkbox'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d224e93f-b556-4ba4-8536-caae8ec24de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6139c732-44a3-4601-8ef6-49aef684564b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer</value>
      <webElementGuid>43f87609-a7b8-4c2c-8244-28f849b4c2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf0afda5-0d1f-4a42-ac1c-5824f65212ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings-group-settings-group&quot;)/div[@class=&quot;relative rounded-lg rounded-br-none rounded-bl-none&quot;]/table[@class=&quot;w-full !border-separate !border-spacing-0 border !border-solid !border-general-100 !border-t-0 !border-l-0 !border-r-0 !rounded-lg&quot;]/tbody[@class=&quot;[&amp;_tr:last-of-type>td]:!border-b-0 [&amp;_tr:last-of-type>td:last-child]:!rounded-br-lg [&amp;_tr:last-of-type>td:first-child]:!rounded-bl-lg&quot;]/tr[@class=&quot;!text-general-800 dark:text-general-50 bg-transparent dark:bg-transparent focus:outline-none focus:outline-offset-0 transition duration-200 cursor-pointer&quot;]/td[@class=&quot;[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap transition duration-200&quot;]/span[@class=&quot;flex justify-center items-center&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-checkbox p-component relative w-4 h-4 shrink-0 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer&quot;]</value>
      <webElementGuid>12f5e05b-e744-4400-a8ef-088e5e922928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>3323fb72-eef6-4c4d-9b0c-89253715590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings-group-settings-group']/div/table/tbody/tr/td/span/label/div/input</value>
      <webElementGuid>1826e612-1d01-4ea0-8eef-2a0cf3e18986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>be7aab87-54ef-4ca1-88ae-3901e09dcb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>a727a869-34c0-42f8-a28a-2ecdc4a5ba48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
