<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Bulk action</name>
   <tag></tag>
   <elementGuidId>51f95992-5d72-4acc-86e8-9c7c32ba0ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Default']/following-sibling::button[@data-ts-section='tree-node-menu-toggler']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bulk Action&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd8efb1c-3bab-45ec-84a1-19470e197358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>809c1169-3f98-4df7-adb7-1cec56de6e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bulk Action</value>
      <webElementGuid>1957f8bd-db1b-4f2f-b254-ea7a4a927eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>bulkaction-overlay-menu</value>
      <webElementGuid>f346989e-3a73-4333-8a96-d6a4ed78f295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-6 items-center transition-all shrink-0 relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] gap-1 flex-row-reverse px-3 py-[7.6px] min-w-[26px] ring-inset shadow-sm rounded bg-transparent text-primary dark:text-primary-300 ring-1 ring-primary hover:bg-primary-bg-weak dark:hover:bg-primary-900 focus-visible:bg-primary-50 hover:bg-primary-bg-weak focus-visible:ring-1 focus-visible:ring-primary-600 dark:focus-visible:ring-primary-600 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none</value>
      <webElementGuid>93ba0d14-85c0-4d4a-9549-e8dccaf33371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ts-section</name>
      <type>Main</type>
      <value>ts-bulkaction-button</value>
      <webElementGuid>f7a1b2ae-c941-4c33-b972-afe740e66fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5cb97d4-49e4-4a6e-a09c-dae9a340f799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>6d16f1da-e2ce-4e90-8b26-6890d1603c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk Action</value>
      <webElementGuid>46d6a776-e249-478a-97ba-8478c61f227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@tagsamurai/ts-mfe-settings-user&quot;)/div[@class=&quot;single-spa-container&quot;]/div[@class=&quot;rounded-lg bg-surface-0 dark:!bg-grayscale-900 text-general-800 dark:text-general-800&quot;]/div[@class=&quot;flex flex-col gap-3 p-6&quot;]/div[@class=&quot;flex flex-col gap-3 text-general-800 dark:text-general-100&quot;]/div[@class=&quot;flex flex-row justify-between items-center&quot;]/div[1]/div[@class=&quot;flex gap-2 items-center text-xs font-medium align-center&quot;]/button[@class=&quot;h-6 items-center transition-all shrink-0 relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] gap-1 flex-row-reverse px-3 py-[7.6px] min-w-[26px] ring-inset shadow-sm rounded bg-transparent text-primary dark:text-primary-300 ring-1 ring-primary hover:bg-primary-bg-weak dark:hover:bg-primary-900 focus-visible:bg-primary-50 hover:bg-primary-bg-weak focus-visible:ring-1 focus-visible:ring-primary-600 dark:focus-visible:ring-primary-600 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none&quot;]</value>
      <webElementGuid>48e140e8-7d69-41f3-bb61-f9404756996c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[35]</value>
      <webElementGuid>63e7cf27-6985-481c-aafd-e188cd3c5369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-settings-user']/div/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>63b23de5-26a9-4b38-8f33-18b7c094dc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//span[text()='Default']/following-sibling::button[@data-ts-section='tree-node-menu-toggler']</value>
      <webElementGuid>b0d7d3bb-d0e5-47e1-a5ec-bb6da6b6fdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::button[1]</value>
      <webElementGuid>23b586dc-f9d5-4c2d-bbb5-48ae5938b5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>319f62f0-17a4-4a52-89c0-8822474be098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Bulk Action' or . = 'Bulk Action')]</value>
      <webElementGuid>a9d092dc-7253-4ba7-a428-a51ab69af4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
