<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chekbox - Select single</name>
   <tag></tag>
   <elementGuidId>7b470b32-8753-492d-bf09-93c08a8118f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='settings-group-settings-group']/div/table/tbody/tr[1]/td/span/label/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;settings-group-settings-group&quot;)/div[@class=&quot;relative rounded-lg rounded-br-none rounded-bl-none&quot;]/table[@class=&quot;w-full !border-separate !border-spacing-0 border !border-solid !border-general-100 !border-t-0 !border-l-0 !border-r-0 !rounded-lg&quot;]/tbody[@class=&quot;[&amp;_tr:last-of-type>td]:!border-b-0 [&amp;_tr:last-of-type>td:last-child]:!rounded-br-lg [&amp;_tr:last-of-type>td:first-child]:!rounded-bl-lg&quot;]/tr[@class=&quot;!text-general-800 dark:text-general-50 bg-transparent dark:bg-transparent focus:outline-none focus:outline-offset-0 transition duration-200 cursor-pointer&quot;]/td[@class=&quot;[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap transition duration-200&quot;]/span[@class=&quot;flex justify-center items-center&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-checkbox p-component relative w-4 h-4 shrink-0 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer&quot;][count(. | //*[@type = 'checkbox']) = count(//*[@type = 'checkbox'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c69ba5-e601-4e5d-8504-e5603406b9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8981db32-ff76-4fe7-ba0d-f7c47bcc0f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer</value>
      <webElementGuid>aeac2c9b-ce9a-4f5e-a700-8cacd5f9b6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b214e0b7-9398-43f5-a41c-b400a1a3c296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings-group-settings-group&quot;)/div[@class=&quot;relative rounded-lg rounded-br-none rounded-bl-none&quot;]/table[@class=&quot;w-full !border-separate !border-spacing-0 border !border-solid !border-general-100 !border-t-0 !border-l-0 !border-r-0 !rounded-lg&quot;]/tbody[@class=&quot;[&amp;_tr:last-of-type>td]:!border-b-0 [&amp;_tr:last-of-type>td:last-child]:!rounded-br-lg [&amp;_tr:last-of-type>td:first-child]:!rounded-bl-lg&quot;]/tr[@class=&quot;!text-general-800 dark:text-general-50 bg-transparent dark:bg-transparent focus:outline-none focus:outline-offset-0 transition duration-200 cursor-pointer&quot;]/td[@class=&quot;[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap transition duration-200&quot;]/span[@class=&quot;flex justify-center items-center&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-checkbox p-component relative w-4 h-4 shrink-0 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer disabled:cursor-default w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none appareance-none transition-all duration-200 cursor-pointer&quot;]</value>
      <webElementGuid>f280dfb0-7d73-4826-8cdd-964140f44407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>498c09b3-1ce8-423e-9ed4-d89a733398cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings-group-settings-group']/div/table/tbody/tr/td/span/label/div/input</value>
      <webElementGuid>f78cd329-16e9-4066-9f17-0ca94d8e87a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>6c7c9b3a-d3ef-4e14-9a92-d6c815251520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>5351c7e1-4ef6-4bad-ab28-7bfc78e3d1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
