<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toast - Success</name>
   <tag></tag>
   <elementGuidId>1c64e40f-01f4-4fce-ad57-e26c3bc5fa1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), 'Success') or contains(., 'Success')) and @data-pc-section = 'detail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>abfe6d6e-735e-4727-8c39-4ef064eda02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success</value>
      <webElementGuid>35be87e4-91fc-457f-ab44-d853b317cf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>detail</value>
      <webElementGuid>930ed917-2828-4b13-9e19-69c8bbd32d30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
